[build]
target = "x86_64-linux.json"
rustflags = [
        "-Ccode-model=kernel",
        "-Cembed-bitcode=n",
        "-Cforce-frame-pointers=y",
        "-Cforce-unwind-tables=n",
        "-Cno-redzone=y",
        "-Crelocation-model=static",
        "-Csymbol-mangling-version=v0",
        "-Ctarget-feature=-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-avx,-avx2",
        "-Zbinary_dep_depinfo=y",
        "-Zfunction-sections=n",
        "-Ztune-cpu=generic",
        "--emit=dep-info,obj",
]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
